from fastapi import FastAPI, HTTPException
from api.database import (
    read_assets,
    write_asset,
    delete_asset_db,
    update_asset_db,
    read_vulns,
    write_vuln,
    update_vuln_db,
    delete_vuln_db,
)
from api.models import Asset, Vulnerability


app = FastAPI(title="LV-MTS API")


# ---- Asset Endpoints ----
@app.get("/assets")
def get_assets():
    return read_assets()


@app.post("/assets", status_code=201)
def add_asset(asset: Asset):
    # ID is autogenerated by database layer
    created_id = write_asset(asset.dict())
    return {"message": "Asset added", "id": created_id}


@app.put("/assets/{aid}")
def update_asset(aid: int, payload: dict):
    assets = read_assets()
    if not any(a["id"] == aid for a in assets):
        raise HTTPException(404, "Asset not found")
    update_asset_db(aid, payload)
    return {"message": "Asset updated"}


@app.delete("/assets/{aid}")
def remove_asset(aid: int):
    assets = read_assets()
    if not any(a["id"] == aid for a in assets):
        raise HTTPException(404, "Asset not found")
    delete_asset_db(aid)
    return {"message": "Asset deleted"}


# ---- Vulnerability Endpoints ----
@app.get("/vulnerabilities")
def get_vulns():
    return read_vulns()


@app.post("/vulnerabilities", status_code=201)
def add_vuln(vuln: Vulnerability):
    created_vuln = vuln.dict()
    write_vuln(created_vuln)
    return {"message": "Vulnerability added", "id": created_vuln.get("id")}


@app.put("/vulnerabilities/{vid}")
def update_vuln(vid: int, payload: dict):
    vulns = read_vulns()
    if not any(v["id"] == vid for v in vulns):
        raise HTTPException(404, "Vulnerability not found")
    update_vuln_db(vid, payload)
    return {"message": "Updated successfully"}


@app.delete("/vulnerabilities/{vid}")
def remove_vuln(vid: int):
    vulns = read_vulns()
    if not any(v["id"] == vid for v in vulns):
        raise HTTPException(404, "Vulnerability not found")
    delete_vuln_db(vid)
    return {"message": "Vulnerability deleted"}
